In [9]:
a=[1,2,3]
for k in range(0,3):
   a[k]=a[k]+1
   print (a)

[2, 2, 3]
[2, 3, 3]
[2, 3, 4]


In [11]:
from numpy import *
a=array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [15]:
output=[n for n in range(10)]
array(output)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
array([2.0*k**0.563 for k in range(0,10,2)])

array([0.        , 2.95467613, 4.36505551, 5.48440035, 6.44866265])

In [19]:
ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
arange(5)

array([0, 1, 2, 3, 4])

In [28]:
arange(0,16,3)

array([ 0,  3,  6,  9, 12, 15])

In [33]:
x=linspace(-pi,pi,10)
print(x)

[-3.14159265 -2.44346095 -1.74532925 -1.04719755 -0.34906585  0.34906585
  1.04719755  1.74532925  2.44346095  3.14159265]


In [35]:
array([1.0,1+1j,'hello']) #array data is upcast to strings

array(['1.0', '(1+1j)', 'hello'], dtype='<U64')

In [38]:
array([1.0,2.0,3.0,4.0],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [40]:
a=array([1,2,3,4])
5.0*a #This gets upcasted because 5.0 is a float

array([ 5., 10., 15., 20.])

In [41]:
N=20
# generate a list from 2->N
numbers = []
for i in range(2,N+1):                 # This can be replaced by array
    numbers.append(i)
# Run Seive of Eratosthenes algorithm marking nodes with -1
for j in range(N-1):
    if numbers[j]!=-1:
        p=numbers[j]
        for k in range(j+p,N-1,p):     # This can be replaced by array
            numbers[k]=-1
# Collect all elements not -1 (these are the primes)
primes = []
for i in range(N-1):                   # This can be replaced by array
    if numbers[i]!=-1:
        primes.append(numbers[i])
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19]
